server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lost_found_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.campuslostsearch.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
  expiration: 86400000  # 24小时

file:
  upload:
    path: /path/to/upload/directory

logging:
  level:
    com.example.campuslostsearch: debug
  file:
    name: logs/application.log

